### ISSUE TITLE
Ansible Galaxy Link is dead

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/ansible#1]
When clicking on <https://galaxy.ansible.com/cobbler/cobbler> this points to a nonexisting collection.

@opoplawski Is it possible if you could have a look why this link is dead?

**Comment by opoplawski** [comment]
I managed to get the inventory plugin into the community.general collection, so I think we should just delete this repository.

**Comment by SchoolGuy** [comment]
@opoplawski Okay so where would be the new primary source for the content of this repository then?

**Comment by opoplawski** [comment]
https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/cobbler.py

**Comment by opoplawski** [comment]
https://galaxy.ansible.com/community/general

**Comment by SchoolGuy** [comment]
Okay I will put this - and only this - in the README and then archive this repository.

**Comment by SchoolGuy** [comment]
Closed by aa6f22dfab5e6b52a729cce9a3880ff70d4141c9
